# -*- coding: utf-8 -*-
"""Copy of AI_Canteen_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvSprlRRvvXkrfSbXrRLXUR3zu1qql-N

# 🍱 AI Canteen — Nhận diện khay cơm
Chạy lần lượt từng cell theo thứ tự.
"""

# CELL 1 — Cài thư viện
!pip install flask flask-cors pyngrok pillow tensorflow numpy -q

# CELL 2 — Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
print('✅ Drive đã mount!')

# CELL 3 — Cấu hình đường dẫn
import os

MODEL_PATH        = '/content/drive/MyDrive/final/best_mmodel(2).h5'
CLASS_INDICES_PATH = '/content/drive/MyDrive/final/class_indices (1).json'

print('Model tồn tại:', os.path.exists(MODEL_PATH))
print('Class indices tồn tại:', os.path.exists(CLASS_INDICES_PATH))

# CELL 4+5 GỘP — Load model + tất cả hàm cần thiết
import json, base64
import numpy as np
import tensorflow as tf
from PIL import Image
from io import BytesIO

# Load model
print('Đang load model...')
model = tf.keras.models.load_model(MODEL_PATH)
print('✅ Load model thành công!')

# Load class indices
with open(CLASS_INDICES_PATH, 'r', encoding='utf-8') as f:
    class_indices = json.load(f)
idx_to_class = {v: k for k, v in class_indices.items()}

# Build bảng giá
import re
PRICE_BY_STT = {
    1: 10000, 2: 25000, 3: 30000, 4: 30000, 5: 25000,
    6: 10000, 7: 30000, 8: 7000,  9: 10000, 10: 25000,
}
def extract_stt(class_name):
    m = re.match(r'^(\d+)\.', class_name.strip())
    return int(m.group(1)) if m else None
def clean_name(class_name):
    return re.sub(r'^\d+\.\s*', '', class_name.strip())

MENU_PRICES, DISPLAY_NAMES = {}, {}
for class_name in class_indices.keys():
    stt = extract_stt(class_name)
    MENU_PRICES[class_name]   = PRICE_BY_STT.get(stt, 0) if stt else 0
    DISPLAY_NAMES[class_name] = clean_name(class_name) if stt else class_name

# Hàm predict 1 ngăn
def predict_compartment(crop: Image.Image, size=(224, 224)):
    arr = np.array(crop.resize(size, Image.LANCZOS)) / 255.0
    arr = np.expand_dims(arr, 0)
    preds = model.predict(arr, verbose=0)
    idx  = int(np.argmax(preds[0]))
    conf = float(np.max(preds[0]))
    return idx_to_class.get(idx, 'Không xác định'), conf

# Hàm nhận crops từ JS
def analyze_tray_crops(crops_data):
    results, total = [], 0
    for item in crops_data:
        img_bytes = base64.b64decode(item['base64'])
        crop = Image.open(BytesIO(img_bytes)).convert('RGB')
        cls, conf = predict_compartment(crop)
        price  = MENU_PRICES.get(cls, 0)
        display = DISPLAY_NAMES.get(cls, cls)
        total += price
        results.append({
            'compartment': item['name'],
            'food_name':   display,
            'raw_class':   cls,
            'confidence':  round(conf * 100, 1),
            'price':       price,
            'crop_image':  item['base64'],
        })
    return results, total

print('✅ Tất cả hàm sẵn sàng!')
print(f'✅ {len(idx_to_class)} món: {list(DISPLAY_NAMES.values())}')

# CELL 6 — Upload HTML mới
from google.colab import files
uploaded = files.upload()  # chọn file index_new.html vừa download

import os
uploaded_name = list(uploaded.keys())[0]
print(f'✅ Đã upload: {uploaded_name}')

# Lưu vào biến để dùng ở cell sau
HTML_FILE_PATH = f'/content/{uploaded_name}'
print(f'Path: {HTML_FILE_PATH}')

# CELL 7 — Tạo Flask server
from flask import Flask, request, jsonify, Response
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

with open(HTML_FILE_PATH, 'r', encoding='utf-8') as f:
    HTML_CONTENT = f.read()

@app.route('/')
def index():
    return Response(HTML_CONTENT, mimetype='text/html')

@app.route('/analyze', methods=['POST'])
def analyze():
    try:
        data = request.get_json()
        print('📦 Keys nhận được:', list(data.keys()) if data else 'None')
        print('📦 crops có không:', 'crops' in data if data else False)

        if not data:
            return jsonify({'error': 'Không có data'}), 400

        if 'crops' in data:
            results, total = analyze_tray_crops(data['crops'])
        elif 'image' in data:
            img_data = data['image']
            if ',' in img_data:
                img_data = img_data.split(',')[1]
            image_bytes = base64.b64decode(img_data)
            results, total = analyze_tray(image_bytes)
        else:
            return jsonify({'error': 'Thiếu crops hoặc image'}), 400

        return jsonify({'success': True, 'items': results, 'total': total})

    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/health')
def health():
    return jsonify({'status': 'ok'})

print('✅ Flask server cấu hình xong!')

# CELL 8 — Stop thread cũ + Start lại ngrok + Flask
import os, signal, threading
from pyngrok import ngrok

# Ngắt tất cả tunnel ngrok cũ
ngrok.kill()

# Flask không có cách stop thread daemon sạch trong Colab
# → Restart runtime nếu vẫn còn lỗi, hoặc dùng cách dưới:


NGROK_TOKEN = '3ERL0z7QnLJGyKCcW4DAaVcdadr_3KvV7MaoMorEMA3zqph3m'
ngrok.set_auth_token(NGROK_TOKEN)

public_url = ngrok.connect(5000)
print(f'\n🌐 APP ĐANG CHẠY TẠI:\n   {public_url}')

def run_flask():
    app.run(port=5000, use_reloader=False, debug=False)

t = threading.Thread(target=run_flask)
t.daemon = True
t.start()

import time
while True:
    time.sleep(60)