# -*- coding: utf-8 -*-
"""MODELTRAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfQtGkT3nRDu6IwP5qftjQflzqJJ1m0t
"""


# ══════════════════════════════════════════════════════════════
# CELL 1 — SETUP & CONFIG
# ══════════════════════════════════════════════════════════════

from google.colab import drive
drive.mount('/content/drive')

import os, json, shutil, random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers, callbacks
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

print("TF:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))
tf.keras.mixed_precision.set_global_policy('mixed_float16')

DATASET_ROOT = "/content/drive/MyDrive/AI CUỐI KỲ"   # thư mục chứa 10 folder món ăn
SAVE_DIR     = "/content/drive/MyDrive/canteen_output" # nơi lưu model + kết quả


SPLIT_DIR    = "/content/canteen_split"   # lưu train/val local (nhanh hơn Drive)
IMG_SIZE     = 224
BATCH_SIZE   = 32
NUM_CLASSES  = 10
SEED         = 42

# Phase 1 — chỉ train head
P1_EPOCHS    = 25
P1_LR        = 1e-3

# Phase 2 — fine-tune top blocks
P2_EPOCHS    = 40
P2_LR        = 1e-5
UNFREEZE_BLOCK = 13    # unfreeze block_13 → block_16 (dataset nhỏ dùng 13, lớn dùng 10)

DROPOUT      = 0.4
L2           = 1e-4
VAL_RATIO    = 0.2

os.makedirs(SAVE_DIR, exist_ok=True)
tf.random.set_seed(SEED); np.random.seed(SEED); random.seed(SEED)
print("✅ Config OK")


# ══════════════════════════════════════════════════════════════
# CELL 2 — KIỂM TRA DATASET
# ══════════════════════════════════════════════════════════════

print(f"\nKiểm tra: {DATASET_ROOT}\n")
total_imgs = 0
class_counts = {}

for item in sorted(os.listdir(DATASET_ROOT)):
    full_path = os.path.join(DATASET_ROOT, item)
    if not os.path.isdir(full_path):
        continue
    imgs = [f for f in os.listdir(full_path)
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.bmp'))]
    class_counts[item] = len(imgs)
    total_imgs += len(imgs)
    status = "✅" if len(imgs) >= 50 else "⚠️ " if len(imgs) >= 20 else "❌"
    print(f"  {status} {item:30s} {len(imgs):4d} ảnh")

print(f"\nTổng: {total_imgs} ảnh | {len(class_counts)} class")
print("\n💡 Khuyến nghị: mỗi class >= 50 ảnh để train tốt")
if len(class_counts) < 10:
    print("⚠️  Thiếu class! Kiểm tra lại tên thư mục.")


# ══════════════════════════════════════════════════════════════
# CELL 3 — AUTO SPLIT TRAIN / VAL
# ══════════════════════════════════════════════════════════════

# Xóa split cũ nếu có
if os.path.exists(SPLIT_DIR):
    shutil.rmtree(SPLIT_DIR)
    print("Đã xóa split cũ")

random.seed(SEED)
print(f"\nSplit {int((1-VAL_RATIO)*100)}/{int(VAL_RATIO*100)} → {SPLIT_DIR}\n")

for class_name in sorted(os.listdir(DATASET_ROOT)):
    src = os.path.join(DATASET_ROOT, class_name)
    if not os.path.isdir(src):
        continue

    imgs = [f for f in os.listdir(src)
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.bmp'))]
    random.shuffle(imgs)

    n_val = max(1, int(len(imgs) * VAL_RATIO))
    splits = {"val": imgs[:n_val], "train": imgs[n_val:]}

    for split, files in splits.items():
        dest = os.path.join(SPLIT_DIR, split, class_name)
        os.makedirs(dest, exist_ok=True)
        for f in files:
            src_file_path = os.path.join(src, f)
            try:
                shutil.copy2(src_file_path, os.path.join(dest, f))
            except FileNotFoundError:
                print(f"⚠️  File not found and skipped: {src_file_path}")

    print(f"  {class_name}: {len(splits['train'])} train | {n_val} val")

print(f"\n✅ Split xong!")


# ══════════════════════════════════════════════════════════════
# CELL 4 — DATA GENERATORS + CLASS WEIGHTS
# ══════════════════════════════════════════════════════════════

train_datagen = ImageDataGenerator(
    rescale            = 1./255,
    rotation_range     = 25,
    width_shift_range  = 0.15,
    height_shift_range = 0.15,
    zoom_range         = 0.25,
    brightness_range   = [0.7, 1.3],
    horizontal_flip    = True,
    vertical_flip      = False,
    shear_range        = 12,
    channel_shift_range= 20,
    fill_mode          = "nearest",
)
val_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    os.path.join(SPLIT_DIR, "train"),
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = "categorical",
    shuffle     = True,
    seed        = SEED,
)
val_gen = val_datagen.flow_from_directory(
    os.path.join(SPLIT_DIR, "val"),
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = "categorical",
    shuffle     = False,
)

print(f"\nTrain: {train_gen.samples} ảnh | Val: {val_gen.samples} ảnh")
print("Classes:", train_gen.class_indices)

# Lưu class_indices (dùng cho inference)
with open(os.path.join(SAVE_DIR, "class_indices.json"), "w", encoding="utf-8") as f:
    json.dump(train_gen.class_indices, f, ensure_ascii=False, indent=2)
print("✅ Saved class_indices.json")

# Class weights — xử lý mất cân bằng dữ liệu
cw_vals = compute_class_weight("balanced", classes=np.unique(train_gen.classes), y=train_gen.classes)
class_weights = dict(enumerate(cw_vals))
print("\nClass weights:", {k: f"{v:.2f}" for k, v in class_weights.items()})

# Preview augmentation
fig, axes = plt.subplots(2, 5, figsize=(15, 6))
batch_x, batch_y = next(train_gen)
idx2cls = {v: k for k, v in train_gen.class_indices.items()}
for i, ax in enumerate(axes.flat):
    if i < len(batch_x):
        ax.imshow(batch_x[i])
        ax.set_title(idx2cls[np.argmax(batch_y[i])].split(". ", 1)[-1], fontsize=7)
    ax.axis("off")
plt.suptitle("Augmented samples", fontsize=11)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "augmentation_preview.png"), dpi=100)
plt.show()


# ══════════════════════════════════════════════════════════════
# CELL 5 — BUILD MODEL (MobileNetV2 + custom head)
# ══════════════════════════════════════════════════════════════

def build_model():
    base = MobileNetV2(
        input_shape = (IMG_SIZE, IMG_SIZE, 3),
        include_top = False,
        weights     = "imagenet",
    )
    base.trainable = False  # Freeze toàn bộ — Phase 1

    inp = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    x = base(inp, training=False)

    # Head
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(512, activation="relu",
                     kernel_regularizer=regularizers.l2(L2),
                     dtype="float32")(x)
    x = layers.Dropout(DROPOUT)(x)
    x = layers.Dense(256, activation="relu",
                     kernel_regularizer=regularizers.l2(L2),
                     dtype="float32")(x)
    x = layers.Dropout(DROPOUT * 0.5)(x)
    out = layers.Dense(NUM_CLASSES, activation="softmax", dtype="float32")(x)

    m = tf.keras.Model(inp, out)
    return m, base

model, base_model = build_model()
model.summary(line_length=80)
print(f"\nTotal params:     {model.count_params():,}")
print(f"Trainable params: {sum(tf.size(w).numpy() for w in model.trainable_weights):,}")


# ══════════════════════════════════════════════════════════════
# CELL 6 — PHASE 1: TRAIN HEAD (base frozen, LR=1e-3)
# ══════════════════════════════════════════════════════════════

print("=" * 55)
print("PHASE 1 — Train classifier head (base FROZEN)")
print("=" * 55)

model.compile(
    optimizer = tf.keras.optimizers.Adam(P1_LR),
    loss      = "categorical_crossentropy",
    metrics   = ["accuracy"],
)

cb1 = [
    callbacks.EarlyStopping(
        monitor="val_accuracy", patience=7,
        restore_best_weights=True, verbose=1),
    callbacks.ReduceLROnPlateau(
        monitor="val_loss", factor=0.5,
        patience=3, min_lr=1e-6, verbose=1),
    callbacks.ModelCheckpoint(
        os.path.join(SAVE_DIR, "best_phase1.h5"),
        monitor="val_accuracy", save_best_only=True, verbose=1),
]

h1 = model.fit(
    train_gen,
    epochs          = P1_EPOCHS,
    validation_data = val_gen,
    class_weight    = class_weights,
    callbacks       = cb1,
    verbose         = 1,
)

best1 = max(h1.history["val_accuracy"])
print(f"\n✅ Phase 1 best val_accuracy: {best1*100:.2f}%")


# ══════════════════════════════════════════════════════════════
# CELL 7 — PHASE 2: FINE-TUNE TOP BLOCKS (LR=1e-5)
# ══════════════════════════════════════════════════════════════

print("=" * 55)
print(f"PHASE 2 — Fine-tune block_{UNFREEZE_BLOCK}→16 (LR={P2_LR})")
print("=" * 55)

# Unfreeze top blocks có chọn lọc
base_model.trainable = True
frozen = 0
unfrozen = 0
for layer in base_model.layers:
    is_top = any(
        f"block_{b}_" in layer.name
        for b in range(UNFREEZE_BLOCK, 17)
    ) or layer.name in ["Conv_1", "Conv_1_bn", "out_relu"]

    if is_top:
        # BatchNorm trong fine-tune nên freeze để ổn định
        if isinstance(layer, layers.BatchNormalization):
            layer.trainable = False
            frozen += 1
        else:
            layer.trainable = True
            unfrozen += 1
    else:
        layer.trainable = False
        frozen += 1

print(f"Unfrozen layers: {unfrozen} | Frozen layers: {frozen}")
print(f"Trainable params: {sum(tf.size(w).numpy() for w in model.trainable_weights):,}")

model.compile(
    optimizer = tf.keras.optimizers.Adam(P2_LR),
    loss      = "categorical_crossentropy",
    metrics   = ["accuracy"],
)

cb2 = [
    callbacks.EarlyStopping(
        monitor="val_accuracy", patience=10,
        restore_best_weights=True, verbose=1),
    callbacks.ReduceLROnPlateau(
        monitor="val_loss", factor=0.3,
        patience=4, min_lr=1e-7, verbose=1),
    callbacks.ModelCheckpoint(
        os.path.join(SAVE_DIR, "canteen_model_best.h5"),   # ← file h5 chính
        monitor="val_accuracy", save_best_only=True, verbose=1),
]

train_gen.reset(); val_gen.reset()

h2 = model.fit(
    train_gen,
    epochs          = P2_EPOCHS,
    validation_data = val_gen,
    class_weight    = class_weights,
    callbacks       = cb2,
    verbose         = 1,
)

best2 = max(h2.history["val_accuracy"])
print(f"\n✅ Phase 2 best val_accuracy: {best2*100:.2f}%")
print(f"📈 Cải thiện: +{(best2 - best1)*100:.2f}%")


# ══════════════════════════════════════════════════════════════
# CELL 8 — PLOT + EVALUATION + SAVE FINAL MODEL
# ══════════════════════════════════════════════════════════════

# ── Plot training history ──────────────────────────────────
def plot_history(h1, h2):
    a1  = h1.history["accuracy"];       va1 = h1.history["val_accuracy"]
    l1  = h1.history["loss"];           vl1 = h1.history["val_loss"]
    a2  = h2.history["accuracy"];       va2 = h2.history["val_accuracy"]
    l2  = h2.history["loss"];           vl2 = h2.history["val_loss"]

    acc   = a1 + a2;  vacc  = va1 + va2
    loss  = l1 + l2;  vloss = vl1 + vl2
    ep    = range(1, len(acc) + 1)
    p1end = len(a1)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Training History — Canteen Model", fontsize=13, fontweight="bold")

    ax1.plot(ep, acc,  color="#2196F3", label="Train")
    ax1.plot(ep, vacc, color="#FF5722", ls="--", label="Val")
    ax1.axvline(p1end, color="gray", ls=":", lw=1.5, label=f"Phase 1/2 (ep {p1end})")
    ax1.set(title="Accuracy", xlabel="Epoch", ylabel="Accuracy")
    ax1.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1))
    ax1.legend(); ax1.grid(alpha=0.3)

    ax2.plot(ep, loss,  color="#2196F3", label="Train")
    ax2.plot(ep, vloss, color="#FF5722", ls="--", label="Val")
    ax2.axvline(p1end, color="gray", ls=":", lw=1.5, label=f"Phase 1/2 (ep {p1end})")
    ax2.set(title="Loss", xlabel="Epoch", ylabel="Loss")
    ax2.legend(); ax2.grid(alpha=0.3)

    plt.tight_layout()
    path = os.path.join(SAVE_DIR, "training_history.png")
    plt.savefig(path, dpi=120, bbox_inches="tight")
    plt.show()
    print(f"Saved: {path}")

plot_history(h1, h2)

# ── Evaluate ──────────────────────────────────────────────
val_gen.reset()
y_prob = model.predict(val_gen, verbose=1)
y_pred = np.argmax(y_prob, axis=1)
y_true = val_gen.classes

idx2cls = {v: k for k, v in val_gen.class_indices.items()}
names   = [idx2cls[i] for i in range(NUM_CLASSES)]
short   = [n.split(". ", 1)[-1] for n in names]

acc_overall = np.mean(y_pred == y_true)
print(f"\n🎯 Overall Val Accuracy: {acc_overall*100:.2f}%\n")
print(classification_report(y_true, y_pred, target_names=names, digits=4))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=short, yticklabels=short,
            linewidths=0.5, ax=ax)
ax.set(title="Confusion Matrix — Val Set",
       xlabel="Predicted", ylabel="True")
plt.xticks(rotation=35, ha="right", fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "confusion_matrix.png"), dpi=120)
plt.show()

# Per-class bar
per_acc = cm.diagonal() / cm.sum(axis=1)
colors  = ["#4CAF50" if a >= .9 else "#FF9800" if a >= .75 else "#F44336"
           for a in per_acc]
fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.barh(short, per_acc * 100, color=colors, edgecolor="white")
for bar, val in zip(bars, per_acc):
    ax.text(bar.get_width() + 1, bar.get_y() + bar.get_height()/2,
            f"{val*100:.1f}%", va="center", fontsize=9)
ax.axvline(90, color="green",  ls="--", alpha=.5, label="90%")
ax.axvline(75, color="orange", ls="--", alpha=.5, label="75%")
ax.set(title="Per-class Accuracy", xlabel="Accuracy (%)", xlim=(0, 115))
ax.legend(); ax.grid(axis="x", alpha=.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "per_class_accuracy.png"), dpi=120)
plt.show()

print("\nPer-class:")
for n, a in zip(names, per_acc):
    s = "✅" if a >= .9 else "⚠️ " if a >= .75 else "❌"
    print(f"  {s} {n}: {a*100:.1f}%")

# ── Save final model ──────────────────────────────────────
final_path = os.path.join(SAVE_DIR, "canteen_model_final.h5")
model.save(final_path)
print(f"\n✅ FINAL MODEL: {final_path}")

# Log JSON
with open(os.path.join(SAVE_DIR, "training_summary.json"), "w", encoding="utf-8") as f:
    json.dump({
        "phase1_val_acc" : round(float(best1), 4),
        "phase2_val_acc" : round(float(best2), 4),
        "overall_val_acc": round(float(acc_overall), 4),
        "per_class"      : {n: round(float(a), 4) for n, a in zip(names, per_acc)},
    }, f, ensure_ascii=False, indent=2)

print("=" * 55)
print(f"🎉 DONE!  Val accuracy = {acc_overall*100:.2f}%")
print(f"📁 Tất cả output lưu tại: {SAVE_DIR}")
print("=" * 55)


# ══════════════════════════════════════════════════════════════
# CELL 9 — (TÙY CHỌN) TEST 1 ẢNH BẤT KỲ
# ══════════════════════════════════════════════════════════════

def predict_single(img_path, top_k=3):
    from tensorflow.keras.preprocessing import image as kimage

    img = kimage.load_img(img_path, target_size=(IMG_SIZE, IMG_SIZE))
    x   = kimage.img_to_array(img) / 255.0
    x   = np.expand_dims(x, 0)

    preds  = model.predict(x, verbose=0)[0]
    top    = np.argsort(preds)[::-1][:top_k]
    idx2c  = {v: k for k, v in train_gen.class_indices.items()}

    # Bảng giá theo đề bài
    PRICE = {
        "1. Cơm trắng"    : 10000,
        "10. Trứng chiên"  : 25000,
        "2. Đậu hũ sốt cà": 25000,
        "3. Cá hú kho"    : 30000,
        "4. Thịt kho trứng": 30000,
        "5. Thịt kho"     : 25000,
        "6. Canh chua"    : 25000,
        "7. Sườn nướng"   : 30000,
        "8. Canh rau"     :  7000,
        "9. Rau xào"      : 10000,
    }

    plt.figure(figsize=(4, 4))
    plt.imshow(img); plt.axis("off")
    lines = [f"#{i+1}  {idx2c[t]}: {preds[t]*100:.1f}%" for i, t in enumerate(top)]
    plt.title("\n".join(lines), fontsize=8, loc="left")
    plt.tight_layout(); plt.show()

    best_cls = idx2c[top[0]]
    print(f"Kết quả: {best_cls}")
    print(f"Giá:     {PRICE.get(best_cls, 0):,} đ")
    return best_cls, PRICE.get(best_cls, 0)

