# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaj7IjFhAEubGZLsmNp2aU0NafAMx7Jr
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import json

model = tf.keras.models.load_model('/content/drive/MyDrive/final/canteen_model_final.h5')

with open('/content/drive/MyDrive/final/class_indices (1).json') as f:
    class_indices = json.load(f)
print(class_indices)  # check thứ tự class có khớp ko

print(model.input_shape)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (224, 224)

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True
)

train_gen = datagen.flow_from_directory(
    '/content/drive/MyDrive/canteen_new_data',
    target_size=IMG_SIZE,
    batch_size=16,
    class_mode='categorical',
    subset='training'
)

val_gen = datagen.flow_from_directory(
    '/content/drive/MyDrive/canteen_new_data',
    target_size=IMG_SIZE,
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

print(train_gen.class_indices)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

# Bắt buộc recompile với optimizer MỚI trước khi fine-tune tiếp
model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('/content/drive/MyDrive/best_mmodel(2).h5', monitor='val_accuracy', save_best_only=True)
]

model.fit(train_gen, validation_data=val_gen, epochs=50, callbacks=callbacks)